# Generated by Django 4.2.7 on 2023-12-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movriesapp', '0005_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movriesapp.genres', verbose_name='Жанр'),
            preserve_default=False,
        ),
    ]
