# Generated by Django 4.2.7 on 2023-12-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movriesapp', '0006_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlike',
            options={'ordering': ['pk'], 'verbose_name': 'Лайки', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
